package generations.gg.generations.core.generationscore.common.world.item

import net.minecraft.core.Holder
import net.minecraft.world.item.Item

val BATTLE_TRANSFORM_ITEMS: Set<Holder<Item>> = setOf(
    GenerationsItems.ABOMASITE,
    GenerationsItems.ABSOLITE,
    GenerationsItems.AERODACTYLITE,
    GenerationsItems.AGGRONITE,
    GenerationsItems.ALAKAZITE,
    GenerationsItems.ALTARIANITE,
    GenerationsItems.AMPHAROSITE,
    GenerationsItems.AUDINITE,
    GenerationsItems.BANETTITE,
    GenerationsItems.BEEDRILLITE,
    GenerationsItems.BLASTOISINITE,
    GenerationsItems.BLAZIKENITE,
    GenerationsItems.CAMERUPTITE,
    GenerationsItems.CHARIZARDITE_X,
    GenerationsItems.CHARIZARDITE_Y,
    GenerationsItems.DIANCITE,
    GenerationsItems.GALLADITE,
    GenerationsItems.GARCHOMPITE,
    GenerationsItems.GARDEVOIRITE,
    GenerationsItems.GENGARITE,
    GenerationsItems.GLALITITE,
    GenerationsItems.GYARADOSITE,
    GenerationsItems.HERACRONITE,
    GenerationsItems.HOUNDOOMINITE,
    GenerationsItems.KANGASKHANITE,
    GenerationsItems.LATIASITE,
    GenerationsItems.LATIOSITE,
    GenerationsItems.LOPUNNNITE,
    GenerationsItems.LUCARIONITE,
    GenerationsItems.MANECTITE,
    GenerationsItems.MAWILITE,
    GenerationsItems.MEDICHAMITE,
    GenerationsItems.METAGROSSITE,
    GenerationsItems.MEWTWONITE_X,
    GenerationsItems.MEWTWONITE_Y,
    GenerationsItems.PIDGEOTITE,
    GenerationsItems.PINSIRITE,
    GenerationsItems.SABLENITE,
    GenerationsItems.SALAMENCITE,
    GenerationsItems.SCEPTILITE,
    GenerationsItems.SCIZORITE,
    GenerationsItems.SHARPEDONITE,
    GenerationsItems.SLOWBRONITE,
    GenerationsItems.STEELIXITE,
    GenerationsItems.SWAMPERTITE,
    GenerationsItems.TYRANITARITE,
    GenerationsItems.VENUSAURITE,
    GenerationsItems.BLUE_ORB,
    GenerationsItems.RED_ORB,
    GenerationsItems.ULTRANECROZIUM_Z
)